### ISSUE TITLE
Error on file size check when tbl_df is too large

### ISSUE THREAD

**Issue by chrisaxelson** [wesm/feather#155] opened 2016-05-20 08:52 UTC
Hi Hadley and Wes,

Thanks so much for a great collaboration with this project! 

When writing and then reading tbl_dfs above a certain size I'm getting the error "Invalid: File is too small to be a well-formed file" (reader.cc line 37). The code below works with 30 million rows, but then fails with 35 million rows (although it did work if I used data.frame).  I've reproduced it on two different computers and get the same error. I tried installing the development version, but couldn't get it to work so this is using the CRAN release. 

````
library(feather)
library(dplyr)

test_length <- 35000000
test_df <- data_frame(Area = rep("Area code", test_length),
                      Birthday = rep("1980-01-01", test_length),
                      Age = rep(36, test_length),
                      ID = rep("Identity_code", test_length),
                      Gender = rep("F", test_length),
                      Year = rep(2014, test_length))

write_feather(test_df, "test_df.feather")
read_feather("test_df.feather")
````

And here's my session info:

R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.2     feather_0.0.1   devtools_1.11.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5     digest_0.6.9    withr_1.0.1     assertthat_0.1  R6_2.1.2        DBI_0.3.1      
 [7] git2r_0.14.0    magrittr_1.5    httr_1.1.0      curl_0.9.7      lazyeval_0.1.10 tools_3.3.0    
[13] parallel_3.3.0  memoise_1.0.0   tibble_1.0

**Comment by Radcliffe** [comment] 2016-05-20 18:54
Having the same issue. I have a data frame with over 16 million rows. Writing the first 7 million rows to feather format creates a 1.9 GB file that I can read successfully, but writing the first 8 million rows creates a 2.2 GB file that I cannot read. 

Error: Invalid: File is too small to be a well-formed file 
4 stop(structure(list(message = "Invalid: File is too small to be a well-formed file", 
    call = NULL, cppstack = NULL), .Names = c("message", "call", 
"cppstack"), class = c("Rcpp::exception", "C++Error", "error", 
"condition"))) 
3 openFeather(path) 
2 feather(path) 
1 read_feather("small.feather") 

R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.9.6 feather_0.0.1   

loaded via a namespace (and not attached):
[1] assertthat_0.1  rsconnect_0.4.3 tools_3.3.0     tibble_1.0      Rcpp_0.12.4     chron_2.3-47

**Comment by wesm** [comment] 2016-05-20 19:14
Hi,

the issue is that `ftell` has undefined behavior for files over 2 GB on certain platforms (e.g. Windows, apparently!), or it may set an error (via `errno`) that we aren't checking. I found some more information here:

http://stackoverflow.com/questions/16696297/ftell-at-a-position-past-2gb

This should not be hard to fix, but will require a patch and a CRAN update.

**Comment by edgararuiz** [comment] 2016-07-07 02:19
Is it a known thing that **data_table** results in comparitively larger (almost 2X) than **data.frame**, both in memory cosumption and file size?  That's why the 35 million row works in data.frame and not in data_table.  It does, however, fail at 70 million rows (which results in a >2GB feather file)

This may be a different feature/issue, ideally, the resulting _feather_ file should be roughly the same size regardless of the package  used.

Here is the code I used:

```
library(feather)
library(dplyr)

test_length <- 500000
test_base <- data.frame(Area = rep("Area code", test_length),
                        Birthday = rep("1980-01-01", test_length),
                        Age = rep(36, test_length),
                        ID = rep("Identity_code", test_length),
                        Gender = rep("F", test_length),
                        Year = rep(2014, test_length))

test_dplyr <- data_frame(Area = rep("Area code", test_length),
                         Birthday = rep("1980-01-01", test_length),
                         Age = rep(36, test_length),
                         ID = rep("Identity_code", test_length),
                         Gender = rep("F", test_length),
                         Year = rep(2014, test_length))

write_feather(test_base, "test_base.feather")
write_feather(test_dplyr, "test_dplyr.feather")

read_feather("test_base.feather")
read_feather("test_dplyr.feather")

print(object.size(test_base))
print(object.size(test_dplyr))

#-------------------- Over 2GB data.frame --------------------------------
test_length <- 70000000

memory.limit(25000)
test_base <- data.frame(Area = rep("Area code", test_length),
                      Birthday = rep("1980-01-01", test_length),
                      Age = rep(36, test_length),
                      ID = rep("Identity_code", test_length),
                      Gender = rep("F", test_length),
                      Year = rep(2014, test_length))
write_feather(test_base, "test_base.feather")
read_feather("test_base.feather")
print(object.size(test_base))
```

**Comment by hadley** [comment] 2016-07-07 12:33
@edgararuiz stringAsFactors

**Comment by edgararuiz** [comment] 2016-07-07 23:49
@hadley You're right, thank you.  When I set the **stringAsFactors** option to **FALSE** in the **data.frame**, both files sizes become identical. And now both crash with 35 million records

```
library(feather)
library(dplyr)

test_length <- 35000000
test_base <- data.frame(Area = rep("Area code", test_length),
                        Birthday = rep("1980-01-01", test_length),
                        Age = rep(36, test_length),
                        ID = rep("Identity_code", test_length),
                        Gender = rep("F", test_length),
                        Year = rep(2014, test_length), stringsAsFactors = FALSE)

test_dplyr <- data_frame(Area = rep("Area code", test_length),
                         Birthday = rep("1980-01-01", test_length),
                         Age = rep(36, test_length),
                         ID = rep("Identity_code", test_length),
                         Gender = rep("F", test_length),
                         Year = rep(2014, test_length))

print(object.size(test_base))
print(object.size(test_dplyr))

write_feather(test_base, "test_base.feather")
write_feather(test_dplyr, "test_dplyr.feather")

print(file.info("test_base.feather")$size)
print(file.info("test_dplyr.feather")$size)

read_feather("test_base.feather")
read_feather("test_dplyr.feather")
```

**Comment by RickPack** [comment] 2016-07-18 17:11
I am also experiencing the read_feather "Invalid: File is too small ... " error with files above about 2 GB in R 3.3.1 (64-bit) through RStudio 0.99.896. I tried to install the current Github package via a download of https://github.com/wesm/feather/archive/master.zip (couldn't get install_github past my work proxy) and an api.h was not found:
`*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=c++0x -I"C:/PROGRA~1/R/R-33~1.1/include" -DNDEBUG -I.   -I"C:/Users/rick.pack/Documents/R/win-library/3.3/Rcpp/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:0:
feather_types.h:2:25: fatal error: feather/api.h: No such file or directory
 #include "feather/api.h"
                         ^
compilation terminated.
make: *** [RcppExports.o] Error 1
Warning: running command 'make -f "
`

**Comment by wesm** [comment] 2016-07-18 22:28
I haven't been able to get to this bug fix yet. Be nice to do it in the next couple weeks and get a bugfix CRAN release out

**Comment by wesm** [comment] 2016-07-18 22:29
(FWIW, the hardest part for me is not having a consistent windows development environment; since Windows is not free even setting up a VM and configuring Visual Studio is a hardship)

**Comment by edgararuiz** [comment] 2016-07-18 22:59
@wesm - Would it be possible for you to develop the fix in the  [online free VS version](https://www.visualstudio.com/products/visual-studio-dev-essentials-vs)?  
For environment testing, I could run the resulting code in a VS Community Ed on my Windows PC 
I'm not experienced in C++ but I'm willing to help test a runtime version if it makes it easier for you
Willing to help where possible

**Comment by RickPack** [comment] 2016-07-20 01:20
I also offer to help although I too lack C++ experience. I have Visual Studio Community 2015 and can get Professional if needed. Maybe a few bits of information would help us assess whether we can help. I admittedly do not know anything about memory management, which I see referenced in related issues like #150 .

**Comment by wesm** [comment] 2016-07-27 23:12
If anyone is motivated to work with big files on Windows, please see #187, the outstanding problems seem to be with MinGW and Windows -- I've run out of debugging steam. Python + Visual Studio on > 2GB files is working fine now.

**Comment by wesm** [comment] 2016-08-02 23:55
This should be fixed by #187. We'll work on getting a release cut, and let me know if you continue to run into any issues

**Closed by wesm** 2016-08-02 23:55 UTC
Labels: bug

**Comment by chrisaxelson** [comment] 2016-08-03 05:25
Thank you so much from all the Windows users out there - sorry it was such a mission!

**Comment by RickPack** [comment] 2016-08-03 14:10
Yes, thank you Wes. I had no idea where to start with this update.
