### ISSUE TITLE
6.2+GB File Read FeatherError: Invalid: File is too small to be a well-formed file

### ISSUE THREAD

**Issue by dragoljub** [wesm/feather#181] opened 2016-06-07 00:27 UTC
I have a DataFrame that looks like this ```Int64Index: 286851 entries, dtypes: float32(3874), float64(925), int64(6), object(22), memory usage: 6.2+ GB```. I can write this to feather format which is pretty quick: ```%time feather.write_dataframe(df2, './slab.fth'), Wall time: 23.7 s```

However when trying to read the 6.2GB file ```!ls -s  ./slab.fth --> 6687872 ./slab.fth ``` I get this error:

```python
%time ft = feather.read_dataframe(r'./slab.fth')
---------------------------------------------------------------------------
FeatherError                              Traceback (most recent call last)
<ipython-input-11-37f78ac6f428> in <module>()
----> 1 get_ipython().magic("time ft = feather.read_dataframe(r'./slab.fth')")

c:\users\ddrmanac\appdata\local\programs\python\python35\lib\site-packages\IPython\core\interactiveshell.py in magic(self, arg_s)
   2161         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2162         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2163         return self.run_line_magic(magic_name, magic_arg_s)
   2164 
   2165     #-------------------------------------------------------------------------

c:\users\ddrmanac\appdata\local\programs\python\python35\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line)
   2082                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2083             with self.builtin_trap:
-> 2084                 result = fn(*args,**kwargs)
   2085             return result
   2086 

c:\users\ddrmanac\appdata\local\programs\python\python35\lib\site-packages\IPython\core\magics\execution.py in time(self, line, cell, local_ns)

c:\users\ddrmanac\appdata\local\programs\python\python35\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194 
    195         if callable(arg):

c:\users\ddrmanac\appdata\local\programs\python\python35\lib\site-packages\IPython\core\magics\execution.py in time(self, line, cell, local_ns)
   1175         else:
   1176             st = clock2()
-> 1177             exec(code, glob, local_ns)
   1178             end = clock2()
   1179             out = None

<timed exec> in <module>()

c:\users\ddrmanac\appdata\local\programs\python\python35\lib\site-packages\feather_format-0.2.0-py3.5-win-amd64.egg\feather\api.py in read_dataframe(path, columns)
     48     df : pandas.DataFrame
     49     """
---> 50     reader = ext.FeatherReader(path)
     51 
     52     # TODO(wesm): pipeline conversion to Arrow memory layout

c:\users\ddrmanac\appdata\local\programs\python\python35\lib\site-packages\feather_format-0.2.0-py3.5-win-amd64.egg\feather\ext.pyx in feather.ext.FeatherReader.__cinit__ (feather/ext.cpp:3016)()

c:\users\ddrmanac\appdata\local\programs\python\python35\lib\site-packages\feather_format-0.2.0-py3.5-win-amd64.egg\feather\ext.pyx in feather.ext.check_status (feather/ext.cpp:1539)()

FeatherError: Invalid: File is too small to be a well-formed file
```

**Comment by hadley** [comment] 2016-06-07 01:07
Duplicate of #162

**Closed by hadley** 2016-06-07 01:07 UTC

**Comment by wesm** [comment] 2016-06-07 18:46
I've been slammed last few weeks but I'd like to get the large file issue fixed soon. Will see what I can do

**Comment by wesm** [comment] 2016-08-02 23:59
This is fixed in master now
