### ISSUE TITLE
Please add support for reading from streams

### ISSUE THREAD

**Issue by adamryczkowski** [wesm/feather#128] opened 2016-04-21 07:28 UTC
I'd like the following code to work:

```
con<-xzfile('/home/adam/dbs/binned_zzal1.feather.xz',open='r')
x<-read_feather(con)
close(con)
```

Thanks.

**Comment by bwlewis** [comment] 2016-07-29 13:34
...duplicate of #69

**Closed** 2016-07-29 14:28 UTC
