### ISSUE TITLE
MAGIC_FEATHER_BYTES in between primitive arrays?

### ISSUE THREAD

**Issue by quinnj** [wesm/feather#182] opened 2016-06-08 05:14 UTC
I'm working on a feather writer for Julia and noticed a peculiarity while trying to match byte-for-byte a feather file I generated from pandas/python. It's based off the Iris data, and the first four columns are doubles. As I was digging into byte differences between my generated file and the pandas-generated file, I noticed that the pandas-generated file has the feather magic bytes `FEA1` after each primitive double array. Is this actually part of the spec? I tried digging around source and couldn't even find where those bytes are being written. I can provide a more concrete example if needed, but just wanted to throw it out there in case there's an easy response.

**Comment by wesm** [comment] 2016-06-08 18:20
Can you clarify? The magic bytes are only written at the beginning and end of the file

see

https://github.com/wesm/feather/blob/master/cpp/src/feather/writer.cc#L51

https://github.com/wesm/feather/blob/master/cpp/src/feather/writer.cc#L73

**Comment by quinnj** [comment] 2016-06-08 21:02
Sure, let me walk you through my steps:

1. Write out the iris.csv dataset as a feather file from python
```python
>>> file = "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/tests/data/iris.csv"
>>> data = pandas.read_csv(file)
>>> data
     SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
...

>>> feather.write_dataframe(data,"/Users/jacobquinn/iris.feather")
```

2. Read the raw bytes in and inspect
```julia
julia> file = Mmap.mmap("/Users/jacobquinn/iris.feather")
7908-element Array{UInt8,1}:
 0x46
 0x45
 0x41
 0x31
 0x66
 0x66
 0x66
...

# first 4 bytes are indeed the MAGIC_FEATHER_BYTES
julia> String(file[1:4])
"FEA1"

# next 1200 bytes are indeed the first primitive DOUBLE array from iris (1200 == 150 rows * 8 bytes each)
julia> reinterpret(Float64, file[5:5+1200-1])
150-element Array{Float64,1}:
 5.1
 4.9
 4.7
 4.6
 5.0
...

# next 4 bytes after that first primitive DOUBLE array are MAGIC_FEATHER_BYTES again
julia> String(file[1205:1208])
"FEA1"

# next 1200 bytes are the next primitive DOUBLE array from iris
julia> reinterpret(Float64, file[1209:1209+1200-1])
150-element Array{Float64,1}:
 3.5
 3.0
 3.2
 3.1
 3.6
 3.9
 3.4
```

The same pattern repeats after each of the arrays that are written (i.e. the magic bytes are written after each array).

**Comment by quinnj** [comment] 2016-06-08 21:26
Obviously this isn't a critical problem because in reading feather files, I'm going based off the metadata offsets for each column (which correctly point to the start of the arrays, taking the magic feather bytes into account), I just thought it was a little odd and not mentioned in the spec docs anywhere. As I mentioned above, I couldn't even find in the `writer.cpp` code where this would be happening.

**Comment by wesm** [comment] 2016-06-08 22:05
I found the issue -- the problem is that the Init() method is being called for each append -- it is supposed to set `initialized_stream_ = true;` before returning. Marking as a bug and will fix soon

**Closed** 2016-06-12 04:22 UTC
Labels: bug
