### ISSUE TITLE
Feather doesn't support a dataframe column of datetime.date objects in Python

### ISSUE THREAD

**Issue by pm8k** [wesm/feather#121] opened 2016-04-12 23:47 UTC
I tried writing out a pandas dataframe to feather, and noticed that my column of datetime.date objects was producing the following error:

``` ---------------------------------------------------------------------------
FeatherError                              Traceback (most recent call last)
<ipython-input-16-b9e7dd094217> in <module>()
----> 1 feather.write_dataframe(df, 'df.feather')

/Users/matthew/anaconda/lib/python2.7/site-packages/feather/api.pyc in write_dataframe(df, path)
     35             name = str(name)
     36 
---> 37         writer.write_array(name, col)
     38 
     39     writer.close()

/Users/matthew/anaconda/lib/python2.7/site-packages/feather/ext.pyx in feather.ext.FeatherWriter.write_array (feather/ext.cpp:2127)()
     86             self.write_timestamp(name, col, mask)
     87         else:
---> 88             self.write_primitive(name, col, mask)
     89 
     90     cdef write_category(self, name, col, mask):

/Users/matthew/anaconda/lib/python2.7/site-packages/feather/ext.pyx in feather.ext.FeatherWriter.write_primitive (feather/ext.cpp:2432)()
    108 
    109         col_values = _unbox_series(col)
--> 110         self.write_ndarray(col_values, mask, &values)
    111         check_status(self.writer.get().AppendPlain(c_name, values))
    112 

/Users/matthew/anaconda/lib/python2.7/site-packages/feather/ext.pyx in feather.ext.FeatherWriter.write_ndarray (feather/ext.cpp:2739)()
    133     cdef int write_ndarray(self, values, mask, PrimitiveArray* out) except -1:
    134         if mask is None:
--> 135             check_status(pandas_to_primitive(values, out))
    136         else:
    137             check_status(pandas_masked_to_primitive(values, mask, out))

/Users/matthew/anaconda/lib/python2.7/site-packages/feather/ext.pyx in feather.ext.check_status (feather/ext.cpp:1543)()
     52 
     53     cdef string c_message = status.ToString()
---> 54     raise FeatherError(frombytes(c_message))
     55 
     56 set_numpy_nan(np.nan)

FeatherError: Invalid: unhandled python type, index 0 
```

I'm going to look to using pandas timestamps in the interim.

**Comment by jreback** [comment] 2016-04-13 00:29
``datetime.date`` are not a first class type in pandas, nor are they likely to be as they have very limited utility.

as well, feather is unlikely to support a non-string-like dtype, IOW this is an actual python ``object`` dtype which is serializable, but not cross language portable.

You should simply use the plethora of support that pandas provides in ``Timestamp``, see docs [here](http://pandas.pydata.org/pandas-docs/stable/timeseries.html).

**Comment by ben519** [comment] 2016-05-27 02:27
Experiencing similar pain with this issue.  In my case I'm processing a large file using R, writing the result to a feather file and trying to read the file using Python.  The dataset contains a Date type column which is generating an error when I try to read the file in Python (but not in R).

R Code
```
library(feather)
df <- data.frame(X=as.Date(c("2013-1-1", "2014-1-1", "2015-1-1")))
write_feather(df, "df.feather")
read_feather("df.feather")  # works
```

Python Code
```
import feather
feather.read_dataframe('df.feather')  # error
```

Error Message
```
NotImplementedErrorTraceback (most recent call last)
<ipython-input-39-4dfedb41c631> in <module>()
----> 1 feather.read_dataframe('df.feather')

//anaconda/envs/datasci/lib/python3.5/site-packages/feather/api.py in read_dataframe(path, columns)
     54     names = []
     55     for i in range(reader.num_columns):
---> 56         name, arr = reader.read_array(i)
     57         data[name] = arr
     58         names.append(name)

//anaconda/envs/datasci/lib/python3.5/site-packages/feather/ext.pyx in feather.ext.FeatherReader.read_array (feather/ext.cpp:3448)()

NotImplementedError: 3
```

**Comment by wesm** [comment] 2016-05-27 19:14
Marked as a bug for now. If someone would be kind enough to look into it, otherwise I may be able to look sometime in the next few weeks

**Comment by ralexx** [comment] 2016-05-31 23:21
Similar problem using Feather 2.0 with Pandas (Python 3.5). In my case it is a Series  of dtype `numpy.timedelta64` within a DataFrame that is breaking `feather.write_dataframe` with `FeatherError: Invalid: unsupported type 22`.

So in /feather/python/feather/ext.pyx, `feather.FeatherWriter.write_array` only gives [special treatment](https://github.com/wesm/feather/blob/b4cc44de55aa0b72d7e216ff7f777a8155495bad/python/feather/ext.pyx#L83-L88) to Pandas Series with categorical dtypes and subclasses of `numpy.datetime64` dtypes. Since there is a corresponding `difftime` class in R, can't `numpy.timedelta64` dtypes be preserved in Feather? 

Code:

```python
import numpy as np
import pandas as pd
import feather

#subset of my data for illustration
df1 = pd.DataFrame(index_df.reset_index().loc[1:3, ['As of Date', 'Ticker', 'ISIN number', 'Description', 'Par_Wtd_Coupon',
       'Maturity_Date', 'TimeToMat']])
df1.head()
```
<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>As of Date</th>
      <th>Ticker</th>
      <th>ISIN number</th>
      <th>Description</th>
      <th>Par_Wtd_Coupon</th>
      <th>Maturity_Date</th>
      <th>TimeToMat</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>1997-01-31</td>
      <td>CECASE</td>
      <td>US125144AE55</td>
      <td>CE CASECNAN</td>
      <td>11.950</td>
      <td>2010-11-15</td>
      <td>5036 days</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1997-01-31</td>
      <td>CHINA</td>
      <td>US712219AA21</td>
      <td>CHINA (PEOPLE'S)</td>
      <td>6.500</td>
      <td>2004-02-17</td>
      <td>2573 days</td>
    </tr>
  </tbody>
</table>
</div>

```python

df1.dtypes
```

    As of Date         datetime64[ns]
    Ticker                     object
    ISIN number                object
    Description                object
    Par_Wtd_Coupon            float64
    Maturity_Date      datetime64[ns]
    TimeToMat         timedelta64[ns]
    dtype: object

```python
feather.write_dataframe(df1, 'write_error.feather')
```


    ---------------------------------------------------------------------------

    FeatherError                              Traceback (most recent call last)

    <ipython-input-98-fdeafa5dd6d3> in <module>()
    ----> 1 feather.write_dataframe(df1, 'write_error.feather')
          2 


    /usr/local/share/anaconda3/lib/python3.5/site-packages/feather/api.py in write_dataframe(df, path)
         35             name = str(name)
         36 
    ---> 37         writer.write_array(name, col)
         38 
         39     writer.close()


    /usr/local/share/anaconda3/lib/python3.5/site-packages/feather/ext.pyx in feather.ext.FeatherWriter.write_array (feather/ext.cpp:2190)()


    /usr/local/share/anaconda3/lib/python3.5/site-packages/feather/ext.pyx in feather.ext.FeatherWriter.write_primitive (feather/ext.cpp:2489)()


    /usr/local/share/anaconda3/lib/python3.5/site-packages/feather/ext.pyx in feather.ext.FeatherWriter.write_ndarray (feather/ext.cpp:2790)()


    /usr/local/share/anaconda3/lib/python3.5/site-packages/feather/ext.pyx in feather.ext.check_status (feather/ext.cpp:1621)()


    FeatherError: Invalid: unsupported type 22

**Comment by wesm** [comment] 2016-06-01 02:25
I'm supportive of adding a Timedelta type to Feather. It's some work, though. See #174

**Comment by ralexx** [comment] 2016-06-01 08:11
@wesm, Point taken. Unfortunately I don't know C++ to be able to work on it.

Looking over @ben519 's issue, `feather.ext.FeatherReader.read_array` appears to be checking for one of (primitive, category, timestamp) [\[0\]](https://github.com/wesm/feather/blob/bbfebbd5bf4b9340ba6ff7af93b8d8c598b6c95e/python/feather/ext.pyx#L179-L190)... 
```python
        check_status(self.reader.get().GetColumn(i, &col))

        cp = col.get()

        if cp.type() == ColumnType_PRIMITIVE:
            values = primitive_to_pandas(cp.values())
        elif cp.type() == ColumnType_CATEGORY:
            values = category_to_pandas(cp)
        elif cp.type() == ColumnType_TIMESTAMP:
            values = timestamp_to_pandas(cp)
        else:
            raise NotImplementedError(cp.type())

        return frombytes(cp.name()), values
```

...in `reader.cc/TableReader::GetColumn` [\[1\]](https://github.com/wesm/feather/blob/bbfebbd5bf4b9340ba6ff7af93b8d8c598b6c95e/cpp/src/feather/reader.cc#L198-L200).

```c++
Status TableReader::GetColumn(int i, std::unique_ptr<Column>* out) const {
  std::shared_ptr<metadata::Column> col_meta = metadata_.GetColumn(i);
  switch (col_meta->type()) {
    case ColumnType::PRIMITIVE:
      RETURN_NOT_OK(GetPrimitive(col_meta, out));
      break;
    case ColumnType::CATEGORY:
      RETURN_NOT_OK(GetCategory(col_meta, out));
      break;
    case ColumnType::TIMESTAMP:
      RETURN_NOT_OK(GetTimestamp(col_meta, out));
      break;
    case ColumnType::DATE:
      RETURN_NOT_OK(GetPrimitive(col_meta, out));
      break;
    case ColumnType::TIME:
      RETURN_NOT_OK(GetTime(col_meta, out));
      break;
    default:
      out->reset(nullptr);
      break;
  }
  return Status::OK();
}
```
 Since `TableReader::GetColumn` has a case for `ColumnType::DATE`, can this dtype check be added to `FeatherReader.read_array` to catch R date objects? E.g.
```python
elif cp.type() in set(ColumnType_TIMESTAMP, ColumnType_DATE, ColumnType_TIME):
            values = timestamp_to_pandas(cp) 
```

**Comment by MGwynne** [comment] 2016-10-31 12:50
Experiencing the same issue as @ben519 , outputting in R works fine (and reading in R), but loading in Python yields:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2.3\helpers\pydev\pydevd.py", line 1580, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2.3\helpers\pydev\pydevd.py", line 964, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  <REMOVED> line 11, in <module>
    df = feather.read_dataframe('data/modelReady.feather')
  <REMOVED> line 93, in read_dataframe
    arr = col.read()
  File "feather\ext.pyx", line 225, in feather.ext.Column.read (feather/ext.cpp:3837)
NotImplementedError: 3
```

Again, working with a Date in R.

**Comment by nickteff** [comment] 2016-12-16 16:46
I have the same issue as @MGwynne, and reading into R is fine, and it was output from an R script.

`Traceback (most recent call last):

  File "<ipython-input-12-bdaa278c0c13>", line 1, in <module>
    df = feather.read_dataframe('modelingWIP.feather')

  File "C:\Users\nteff\AppData\Local\Continuum\Anaconda3\lib\site-packages\feather\api.py", line 93, in read_dataframe
    arr = col.read()

  File "feather/ext.pyx", line 225, in feather.ext.Column.read (feather/ext.cpp:3841)

NotImplementedError: 3`

**Comment by jdossgollin** [comment] 2017-04-12 13:52
Continuing to have this problem here as well -- writing a `data.frame` with a date column in R works, reading it back into R works, but reading it into Python gives the errors described above.

**Comment by xhochy** [comment] 2017-04-13 11:06
With the movement of the Feather code into the https://github.com/apache/arrow codebase, this problem should be gone. There we have implemented the conversion from Pandas columns of `datetime.date` to Arrow and thus to call file format writers using Apache Arrow (i.e. Feather & Parquet at the moment).

**Comment by wesm** [comment] 2017-04-13 14:11
Would be great to add a test case, or at least sample code for reproducing this. @jdossgollin can you give a standalone example reproduction we can use to test this out?

**Comment by jdossgollin** [comment] 2017-04-13 15:07
@wesm sure thing

Contents of file `test_feather.R`: 
```
library(feather)
date_df <- data.frame(date = Sys.Date() + (-5:5), days_back = -5:5)
feather::write_feather(date_df, 'test.feather')
```
Contents of file `test_feather.py`:
```
import feather
df = feather.read_dataframe('test.feather')
```
Results of running together:
```
$ Rscript test_feather.R; python3 test_feather.py
Traceback (most recent call last):
  File "test_feather.py", line 3, in <module>
    df = feather.read_dataframe('test.feather')
  File "/Users/James/anaconda3/lib/python3.6/site-packages/feather/api.py", line 93, in read_dataframe
    arr = col.read()
  File "feather/ext.pyx", line 225, in feather.ext.Column.read (feather/ext.cpp:4296)
NotImplementedError: 3
```

Hopefully I'm not being completely clueless here -- installed following directions from [pypi.python.org/](https://pypi.python.org/pypi/feather-format/). I'm a conda user, so I used `conda install -c conda-forge feather-format`. Just as a check for what I'm working with:
```
# packages in environment at /Users/James/anaconda3:
#
feather-format            0.3.1                    py36_1    conda-forge
```

**Comment by wesm** [comment] 2020-04-10 01:20
This is supported in Feather V2 (coming in pyarrow / Arrow 0.17.0)

**Closed by wesm** 2020-04-10 01:20 UTC
Labels: bug, python
