### ISSUE TITLE
[Question] Anyone working on Feather bindings for NodeJS?

### ISSUE THREAD

**Issue by thibaudh** [wesm/feather#176] opened 2016-06-02 19:06 UTC
I was wondering there is work-in-progress bindings for NodeJS or if anyone is actively working on it. If so, please let me know, we have been thinking of using Feather to serialize graph datasets.

I know FlatBuffer does have JS bindings, so it should not be impossible...

**Comment by hadley** [comment] 2016-08-16 14:56
Duplicate of #17, probably.

**Closed by hadley** 2016-08-16 14:56 UTC
