### ISSUE TITLE
feather incompatible with shinyapps.io?

### ISSUE THREAD

**Issue by mcfrank** [wesm/feather#110] opened 2016-04-08 17:30 UTC
The package is great - but we have had issues pushing to shinyapps.io. Full compilation record is below - simple MWE is [here](https://github.com/mcfrank/feather_mwe). Looks like Kyle Doherty in [the blogpost](http://blog.rstudio.org/2016/03/29/feather/) had this issue also. 

(cc: @mikabr)

---

Preparing to deploy application...DONE
Uploading bundle for application: 93038...DONE
Deploying bundle: 413923 for application: 93038 ...
Waiting for task: 179810067
  building: Building image: 407055
  building: Building package: tibble
  building: Building package: feather
###### ########################## Begin Task Log ################################

[2016-04-08T17:25:33.518724425+0000] Installing R package: digest (0.6.9)
- installing to library ‘/usr/local/lib/R/site-library’
- installing _binary_ package ‘digest’ ...
- DONE (digest)
  [2016-04-08T17:25:33.843182371+0000] Installing R package: mime (0.4)
- installing to library ‘/usr/local/lib/R/site-library’
- installing _binary_ package ‘mime’ ...
- DONE (mime)
  [2016-04-08T17:25:34.134156276+0000] Installing R package: lazyeval (0.1.10)
- installing to library ‘/usr/local/lib/R/site-library’
- installing _binary_ package ‘lazyeval’ ...
- DONE (lazyeval)
  [2016-04-08T17:25:34.438123004+0000] Installing R package: htmltools (0.3)
- installing to library ‘/usr/local/lib/R/site-library’
- installing _binary_ package ‘htmltools’ ...
- DONE (htmltools)
  [2016-04-08T17:25:34.730880927+0000] Installing R package: Rcpp (0.12.4)
- installing to library ‘/usr/local/lib/R/site-library’
- installing _binary_ package ‘Rcpp’ ...
- DONE (Rcpp)
  [2016-04-08T17:25:36.193083213+0000] Installing R package: jsonlite (0.9.19)
- installing to library ‘/usr/local/lib/R/site-library’
- installing _binary_ package ‘jsonlite’ ...
- DONE (jsonlite)
  [2016-04-08T17:25:36.663922090+0000] Installing R package: httpuv (1.3.3)
- installing to library ‘/usr/local/lib/R/site-library’
- installing _binary_ package ‘httpuv’ ...
- DONE (httpuv)
  [2016-04-08T17:25:37.113627752+0000] Installing R package: xtable (1.8-2)
- installing to library ‘/usr/local/lib/R/site-library’
- installing _binary_ package ‘xtable’ ...
- DONE (xtable)
  [2016-04-08T17:25:37.457599177+0000] Installing R package: assertthat (0.1)
- installing to library ‘/usr/local/lib/R/site-library’
- installing _binary_ package ‘assertthat’ ...
- DONE (assertthat)
  [2016-04-08T17:25:37.741146940+0000] Building R package: tibble (1.0)
  /mnt/packages/build /mnt
- installing to library ‘/usr/local/lib/R/site-library’
- installing _source_ package ‘tibble’ ...
  *\* package ‘tibble’ successfully unpacked and MD5 sums checked
  *\* libs
  g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
  g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c matrixToDataFrame.cpp -o matrixToDataFrame.o
  g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o tibble.so RcppExports.o matrixToDataFrame.o -L/usr/lib/R/lib -lR
  installing to /usr/local/lib/R/site-library/tibble/libs
  *\* R
  *\* inst
  *\* preparing package for lazy loading
  *\* help
  **\* installing help indices
  *\* building package indices
  *\* installing vignettes
  *\* testing if installed package can be loaded
- creating tarball
  packaged installation of ‘tibble’ as ‘tibble_1.0_R_x86_64-pc-linux-gnu.tar.gz’
- DONE (tibble)
  /mnt
  [2016-04-08T17:25:43.782191839+0000] Building R package: feather (0.0.0.9000)
  /mnt/packages/build/wesm-feather-f829c69/wesm-feather-f829c69 /mnt
- installing to library ‘/usr/local/lib/R/site-library’
- installing _source_ package ‘feather’ ...
  ./configure: 3: ./configure: rsync: not found
  `../cpp/src/feather/api.h' ->`src/feather/api.h'
  `../cpp/src/feather/buffer.h' ->`src/feather/buffer.h'
  `../cpp/src/feather/common.h' ->`src/feather/common.h'
  `../cpp/src/feather/feather-c.h' ->`src/feather/feather-c.h'
  `../cpp/src/feather/io.h' ->`src/feather/io.h'
  `../cpp/src/feather/metadata.h' ->`src/feather/metadata.h'
  `../cpp/src/feather/metadata_generated.h' ->`src/feather/metadata_generated.h'
  `../cpp/src/feather/mman.h' ->`src/feather/mman.h'
  `../cpp/src/feather/reader.h' ->`src/feather/reader.h'
  `../cpp/src/feather/status.h' ->`src/feather/status.h'
  `../cpp/src/feather/types.h' ->`src/feather/types.h'
  `../cpp/src/feather/writer.h' ->`src/feather/writer.h'
  `../cpp/src/feather/buffer.cc' ->`src/feather/buffer.cc'
  `../cpp/src/feather/feather-c.cc' ->`src/feather/feather-c.cc'
  `../cpp/src/feather/io.cc' ->`src/feather/io.cc'
  `../cpp/src/feather/metadata.cc' ->`src/feather/metadata.cc'
  `../cpp/src/feather/reader.cc' ->`src/feather/reader.cc'
  `../cpp/src/feather/status.cc' ->`src/feather/status.cc'
  `../cpp/src/feather/types.cc' ->`src/feather/types.cc'
  `../cpp/src/feather/writer.cc' ->`src/feather/writer.cc'
  *\* libs
  g++ -std=c++0x -I/usr/share/R/include -DNDEBUG -I.  -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c RcppExports.cpp -o RcppExports.o
  g++ -std=c++0x -I/usr/share/R/include -DNDEBUG -I.  -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c feather-read.cpp -o feather-read.o
  g++ -std=c++0x -I/usr/share/R/include -DNDEBUG -I.  -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c feather-types.cpp -o feather-types.o
  g++ -std=c++0x -I/usr/share/R/include -DNDEBUG -I.  -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c feather-write.cpp -o feather-write.o
  g++ -std=c++0x -I/usr/share/R/include -DNDEBUG -I.  -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c feather/buffer.cc -o feather/buffer.o
  g++ -std=c++0x -I/usr/share/R/include -DNDEBUG -I.  -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c feather/feather-c.cc -o feather/feather-c.o
  g++ -std=c++0x -I/usr/share/R/include -DNDEBUG -I.  -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c feather/io.cc -o feather/io.o
  g++ -std=c++0x -I/usr/share/R/include -DNDEBUG -I.  -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c feather/metadata.cc -o feather/metadata.o
  feather/metadata.cc: In constructor ‘feather::metadata::TableBuilder::TableBuilder()’:
  feather/metadata.cc:181:5: error: type ‘feather::metadata::TableBuilder’ is not a direct base of ‘feather::metadata::TableBuilder’
  g++ -std=c++0x -I/usr/share/R/include -DNDEBUG -I.  -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c feather/reader.cc -o feather/reader.o
  make: **\* [feather/metadata.o] Error 1
  make: **\* Waiting for unfinished jobs....
  ERROR: compilation failed for package ‘feather’
- removing ‘/usr/local/lib/R/site-library/feather’
  ################################# End Task Log ################################# 
  Error: Unhandled Exception: Child Task 179810068 failed: Error building image: Error building feather (0.0.0.9000). Build exited with non-zero status: 1
  Execution halted

**Comment by phillc73** [comment] 2016-04-14 09:25
Duplicate of #67 @hadley Hadley suggests waiting for a CRAN release.

**Closed** 2020-04-10 01:17 UTC
